### ISSUE TITLE
Unable to bind an action to loading a file on demand

### ISSUE THREAD

**Issue by jacobdufault** [JibbSmart/JoyShockMapper#117]
The readme uses this example as a valid command:
```
HOME = "GTA_driving.txt"
```

However, when entering it on version 2.0.3 I get this error
```
Error: "GTA_driving.txt" is not a valid command
Error in entering the command. Enter README to bring up the user manual.
```

Thanks for all the hard work on this project - it overall works really well.

**Comment by JibbSmart** [comment]
Thanks for the feedback :) Just to be sure, do you have a file called "GTA_driving.txt" in the same folder as JoyShockMapper.exe?

**Comment by jacobdufault** [comment]
Creating one does not seem to make a difference. I was trying to look through the code and my best guess is that [this](https://github.com/JibbSmart/JoyShockMapper/blob/4bce7d9665bc5b7e96f0b7438e4e73c8d29fb54a/JoyShockMapper/src/CmdRegistry.cpp#L129) regex is rejecting it, but I didn't test/debug further than that.

**Comment by JibbSmart** [comment]
Hmm... that's weird. Here's what happens when I do it on 2.0.3:
![image](https://user-images.githubusercontent.com/6497881/97532317-0cf30d00-19f1-11eb-9c56-7ca929a0d17c.png)

**Comment by jacobdufault** [comment]
That is strange. I tried passing an absolute path, opening JSM via command prompt, and also opening as admin but none made a difference.

![image](https://user-images.githubusercontent.com/356714/97536450-6409cb00-197a-11eb-8efc-4b2b99385ed9.png)

**Comment by jacobdufault** [comment]
Ah, found the mistake. I was creating a file named "GTA_driving.txt.txt". Sorry about that!

**Comment by jacobdufault** [comment]
(though it'd be great if the error message indicated the file count not be found instead of just invalid command)
