### ISSUE TITLE
DualSense Support.

### ISSUE THREAD

**Issue by rocketbucket10** [JibbSmart/JoyShockMapper#118]
Hi!

Will joyshockmapper have support for DualSense controllers?

**Comment by JibbSmart** [comment]
Hi! I'll add DualSense support myself as soon as I can get it and can get it working. They're not available here yet, but I'll get one as soon as I can. Like with the DS4, expect USB support first.

**Comment by rocketbucket10** [comment]
Thanks for the quick reply!
No need to hurry, take your time with the implementation. :)
I'm only getting the controller next month anyaways, until then I'll use my DS4.
