### ISSUE TITLE
Trying to get GYRO_SENS to work

### ISSUE THREAD

**Issue by Kurren123** [JibbSmart/JoyShockMapper#120]
Hi there. I'm trying to play skyrim and get some more sensitivity on the gyro, but `GYRO_SENS` doesn't seem to work, even when it's set to a crazy value like 32. My config:

```
RESET_MAPPINGS

REAL_WORLD_CALIBRATION = 8
IN_GAME_SENS = 1
GYRO_SENS = 32
R,GYRO_SENS = 4 2 # half speed when aiming
COUNTER_OS_MOUSE_SPEED

# Button mappings
LLEFT = A
LRIGHT = D
LUP = W
LDOWN = S

R = GYRO_OFF
L = NONE
ZR = LMOUSE
ZL = RMOUSE

N = TAB # menu
E = LCONTROL # crouch
W = R # sheath/ready
S = E # action

L3 = ALT # sprint
R3 = NONE
+ = ESC 
- = CALIBRATE

L,L3 = Z # shout
L,- = T # wait
L,E = F5 # Quick save
L,N = SPACE # jump

LEFT_RING_MODE = INNER
LRING = LSHIFT # walk when pushing stick slowly

# Mouse
GyroConfigs/_3Dmouse.txt
```

Any suggestions would be appreciated!

**Edit:** Removing `COUNTER_OS_MOUSE_SPEED` or `IN_GAME_SENS` doesn't affect anything.
Platform: Windows 10
Controller: Switch, bluetooth
Game: Skyrim

**Comment by Kurren123** [comment]
Problem solved! The issue was that the last line is importing settings from `GyroConfigs/_3Dmouse.txt` which overwrites the previous `GYRO_SENS` value.

**Comment by JibbSmart** [comment]
Glad to hear it :)
