### ISSUE TITLE
key list?

### ISSUE THREAD

**Issue by nr1995** [JibbSmart/JoyShockMapper#13]
Sorry for posting this here, since it's not really an issue,
but is there some place where I can see a list of the key names for the config files?
I tried adding    UP = KP_PLUS    to my config file,
since that's what it usually shows up as, and that's what **_Portal_** calls it.
but it didn't work.
Don't know if it's because that key isn't registered,
or because I called it incorrectly.
A comprehensive list of everything that's on a full-size keyboard would be helpful.
Thanks.

**Comment by JibbSmart** [comment]
Hi! Sorry for the delayed response. The README should cover all possible inputs. Currently, the options are:

> 0-9: number keys across the top of the keyboard
> N0-N9: numpad number keys
> F1-F29: F1, F2, F3... etc
> A-Z: letter keys
> UP, DOWN, LEFT, RIGHT: the arrow keys
> LCONTROL, RCONTROL, CONTROL: left Ctrl, right Ctrl, generic Ctrl, respectively
> LALT, RALT, ALT: left Alt, right Alt, generic Alt, respectively
> LSHIFT, RSHIFT, SHIFT: left Shift, right Shift, generic Shift, respectively
> TAB: Tab
> ENTER: Enter
> LMOUSE, MMOUSE, RMOUSE: mouse left click, middle click, right click, respectively
> SCROLLUP, SCROLLDOWN: scroll the mouse wheel up, down, respectively
> PAGEUP, PAGEDOWN, HOME, END, INSERT, DELETE, BACKSPACE
> NONE: No input
> CALIBRATE: recalibrate gyro when pressing this input
> GYRO_ON, GYRO_OFF: Enable or disable gyro
> GYRO_INVERT, GYRO_INV_X, GYRO_INV_Y: Invert gyro, or in just the x or y axes, respectively
> ; ' , . / \ [ ] + -

If you're saying d-pad up should be the + key, it looks like this:
UP = +
