### ISSUE TITLE
Wii remote support

### ISSUE THREAD

**Issue by Terramoto** [JibbSmart/JoyShockMapper#15]
Hello,

How easy could wii remote support be added to this? Mine is connected but on Steam it doesn't display the gyroscope settings just as a generic 360 controller, however during the controller configuration is detects the gyro axis and attachs them to the keys. I'm guessing its just missing the proper controller layout for steam.

**Comment by JibbSmart** [comment]
It wouldn't be easy, to be honest. I'd have to get my hands on a Wiimote and MotionPlus. I'd have to find good resources for how to interpret the data that comes out of it, although I'm sure there are plenty such resources online. But it'd take some time, and isn't a priority compared to other things at the moment.

Thanks for the suggestion, though!
