### ISSUE TITLE
Conflict when using hold and double press on the same button.

### ISSUE THREAD

**Issue by OscarSenlis** [JibbSmart/JoyShockMapper#22]
Using this configuration :
```
N = A B
N,N = C
```
It is impossible to activate the B key. Holding N activates A.

Hi! I am currently working on a config file for Half-Life 2 and I discovered this behavior.
Thanks for your work!

**Comment by JibbSmart** [comment]
Thanks for the heads-up! I'll have a look.

**Comment by OscarSenlis** [comment]
Update : the same behavior occurs in the 1.6.0 release.

**Comment by JibbSmart** [comment]
Thanks for checking. I hadn't looked into it yet because 1.6 was such a big change to everything. But I'll have a look.

**Comment by OscarSenlis** [comment]
The behavior is now correct in the 2.0.0 release.
