### ISSUE TITLE
When using controller as a cursor or mouse, there is an application incompatibility.

### ISSUE THREAD

**Issue by And-OnceAgain** [JibbSmart/JoyShockMapper#24]
Hi, I'm not too sure how to phrase this but I'll try my best.

I made a txt file in the autoload folder, called Explorer.exe so that I could use the controller as a mouse with gyro and stick.   Everything seems to be working fine with one exception.

I purchased a program from Called Stardock Groupy, and while I'm not too certain how it achieves it's function, I can sort of describe what it does.

Basically it wrangles application windows and applies internet-browser-like tabs to them.   It works for windows file explorer (windows 10) and most applications that have a title bar. 

The issue is that, while I can use the application fine with a standard mouse, as soon as I start using JoyShockMapper to control my cursor, Groupy won't respond to anything I do.   It doesn't crash,   It just won't do anything when I click on the tabs.   I can still use the standard mouse to interact with Groupy at that point.

So that brings me to now, where I am not sure how you'll be able to investigate without buying the program. 

SO.    If I offer to buy the program for you, could you try and investigate the issue and see what you can do?   I love JoyShockMapper, and if I knew anything about code I would contribute the solution free of charge XD       

Thanks so much for reading this far and I hope you stay safe with everything that's going on.

**Comment by JibbSmart** [comment]
Oof, that's rough! Very kind of you to offer to help financially. I think there are a couple of things to explore here before we get there, if you don't mind:

First, have you tried running JoyShockMapper as administrator? I've seen something like this before where games that run with different privileges to JoyShockMapper don't respond to it. It sounds like Groupy could be the kind of thing that needs admin privileges.

Second, it could be that Groupy doesn't play nicely with other tools either. DS4Windows, for example, if you're using a DS4. If that's the case, that might help narrow down the problem.

It might be that Groupy doesn't respond to virtual mouse events, but rather explicitly looks for events from connected devices. If that's the case, I think DS4Windows wouldn't work either. JSM could fix this by acting as a driver for a virtual mouse (as far as any application would be concerned, it's a physically connected device), but that's a big change. It is one that I'm exploring the possibility of, though, for similar reasons with other software (for example, Valorant won't work with JSM and similar programs, but will work with reWASD, which creates a virtual device).

I hope you're staying safe, too! Take care

**Comment by And-OnceAgain** [comment]
Wow.   The solution was actually to launch JSM as administrator.    Thanks so much XD
If anything can be gained from this it is that I shall never again underestimate the importance of admin privileges.

**Comment by JibbSmart** [comment]
I'm so glad that worked :) Thanks for letting me know!
