### ISSUE TITLE
Mapping to XInput?

### ISSUE THREAD

**Issue by ericcruzlima** [JibbSmart/JoyShockMapper#32]
Great software, saddly doesn't seem to map to XInput as well. It may sound crazy but some games do take advantage of gamepad inputs as well, having the option for mapping to keyboard, mouse AND gamepad makes a huge difference.

Flick-stick is sick tho😉👌

Best feature.

**Comment by JibbSmart** [comment]
Hi! I'm glad you like flick stick :) XInput output is something I'd like to add, but it's a very big feature. In the meantime, it can be used at the same time as other remapping software. For example, for DOOM Eternal, I had Steam only output the left stick while JoyShockMapper did everything else.

**Comment by ericcruzlima** [comment]
Awesome. I'll give it a try. thx so much :D
