### ISSUE TITLE
vcruntime140.dll not found error upon initial run

### ISSUE THREAD

**Issue by gkeegan** [JibbSmart/JoyShockMapper#36]
On some systems, this file may not be present. It can be installed simply by going [here](https://www.microsoft.com/en-us/download/details.aspx?id=52685) and running `vc_redist.x86.exe`. Without this file present, JoyShockMapper does not function for the "Player" version.

**Comment by gkeegan** [comment]
Apologies. This is a duplicate of #25.

**Comment by JibbSmart** [comment]
Hi @gkeegan, JoyShockMapper shouldn't need vcruntime140.dll. It's meant to work such that nothing else needs to be installed. A user had this problem with 1.5, and our understanding is that a change in 1.6 fixed this. Is this still a problem?

**Comment by gkeegan** [comment]
@JibbSmart This is in fact an issue still (I am for sure using 1.6).

I will reopen #37 as the "other solution" of having Steam running went away after I restarted. (Uninstalled the manual version the tested with Steam before restarting like a silly person).

**Comment by JibbSmart** [comment]
Thanks. I appreciate the pull request. Those instructions are indeed a super useful workaround, but I've gotta find the root of this problem.

**Comment by gkeegan** [comment]
> I've gotta find the root of this problem.

Agreed. That's why on the new PR I did not mark it as closing this issue, since you have tried to remove this requirement.

**Comment by gkeegan** [comment]
Fixed in 1.6.1.
