### ISSUE TITLE
Technical and methods

### ISSUE THREAD

**Issue by i3130002** [JibbSmart/JoyShockMapper#39]
I was kinda shocked seeing how accurate your system is! Having had the same IMU tracking and not being able to solve drift, I was wondering what amazing thing you guys did to solve the problem! Going through your code wasn't able to find where and how you are solving the drift problem. Please point me to the file(s)/function(s) responsible to solve it. 
Really appreciate it.
Thanks

**Comment by JibbSmart** [comment]
Hi! I'm glad you're interested! By "drift" do you mean the cursor still moving when the controller isn't? It's all explained on GyroWiki:
http://gyrowiki.jibbsmart.com/blog:good-gyro-controls-part-1:the-gyro-is-a-mouse

In my opinion, the best solution is to let players manually calibrate the controller manually. The controller's gyro's bias tends to change very little (if at all) over time, so calibrating once can last for hours. Auto-calibration systems are more prone to errors and introduce unnecessary imprecision. JoyShockMapper allows manual calibration by calling "JslStartContinuousCalibration" to start calibrating and "JslPauseContinuousCalibration" once calibration has completed. Those are JoyShockLibrary functions, and they're just recording the average angular velocity of the gyro over time.
