### ISSUE TITLE
[Question] Is there a way to use gyro mouse input of 8BitDo controllers?

### ISSUE THREAD

**Issue by egeesin** [JibbSmart/JoyShockMapper#56]
As the title said. I'm using 8BitDo SN30 Pro+ (with Switch mode on since it's emulating JoyCon features) I tried connecting through Bluetooth and USB. Followed [Gyro Mouse Input](https://github.com/JibbSmart/JoyShockMapper#4-gyro-mouse-inputs) section. All button/ring/trigger inputs works as intended. But I'm not really sure how to get gyro enabled. Is there any solution or workaround of this? Thanks in advance.

**Comment by JibbSmart** [comment]
Hi! Some users have had this problem with the Pro Controller. I encounter it once in a blue moon. I'm working on a fix, and my hope is that fixes the problem for the 8BitDo, too. I've heard some have had success with that controller, but as I don't have one to test I can't "officially" support it.

**Comment by renandr** [comment]
If you don't have the controller, one should be provided to you by the community :)
I'd be happy to help.
