### ISSUE TITLE
how to convert quaternion into euler angles

### ISSUE THREAD

**Issue by zhengyuedong** [JibbSmart/JoyShockMapper#58]
I use  gyroscope to record ax ,ay , az , gx , gy, gz ，and then I convert them to quaternion. Here comes the questions: how could I probably transform quaternion into euler angles?
 thanks for helping.

**Comment by JibbSmart** [comment]
Hi zhengyuedong,

This is a very big question, and not something that my software has to do. But I've done it a long time ago based on resources like these:
https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles

**Comment by zhengyuedong** [comment]
thanks for sharing. I'm new here and carelessly mistake it as a platform where everyone communicates any bugs.
