### ISSUE TITLE
Unrecognized Commands and Gyro Not functioning in Build from Source

### ISSUE THREAD

**Issue by theofficialgman** [JibbSmart/JoyShockMapper#78]
When I use the precompiled Windows executable I have no issues. 

I am trying to build the source on Windows (from the current master) and the build goes fine with no errors (but a few warnings about loss of data) and gyro doesn't work at all. In addition, the minus and plus buttons are detected as unrecognized commands. I've attached the built exe for reference.
[JoyShockMapper.zip](https://github.com/JibbSmart/JoyShockMapper/files/5019617/JoyShockMapper.zip)

Edit: Just tested by compiling the last release (1.6.1) myself and it has no problems so it is definitely in one of the commits since then.

**Comment by JibbSmart** [comment]
We've had a big refactor that hasn't been fully tested yet. Thanks for noting those problems

**Comment by theofficialgman** [comment]
Actually I figured out that it might be an issue (or an intended feature?) with 1.6.1 that is now changed. I had based my config off of one of yours @JibbSmart  with (+ = ESC) which 1.6.1 interpreted as controller + and now just throws an error. + is being used exclusively as a keyboard map in the new source and the controller uses PLUS (PLUS = ESC)

**Comment by JibbSmart** [comment]
I'll have to have a look into that. I haven't been involved with the refactor, but I don't want to break backwards compatibility

**Comment by theofficialgman** [comment]
Looks like the operators.cpp file was removed which contained the code to transform the + to PLUS and - to MINUS if placed before the =

**Comment by theofficialgman** [comment]
It looks like operators.cpp was added into the source to reintroduce the functionality that used to be in main.cpp but it doesn't work because an unrecognized command is thrown

**Comment by theofficialgman** [comment]
Nonfunctioning gyro and the unrecognized commands have been fixed. Closing this issue.

**Comment by theofficialgman** [comment]
I take that back. Gyro is fixed but + and - legacy references to controller plus and minus have not been re-implemented yet. Looks like it is still being worked on. Reopening for reference.

**Comment by Electronicks** [comment]
Fix in pull request
