### ISSUE TITLE
Virus/Malware warning when downloading 1.3.0 with Firefox

### ISSUE THREAD

**Issue by Zhonecage** [JibbSmart/JoyShockMapper#9]
Yeah I thought I would let you know that Firefox gives a Malware/Virus warning when downloading version 1.3.0 of JSM. There is no warning with older versions.

**Comment by JibbSmart** [comment]
Thanks for the heads-up! I'll look into what might be causing this.

**Comment by Zhonecage** [comment]
I downloaded the newest release (1.4.1) and the warning is gone. Thanks for looking into this. JSM rocks!

**Comment by JibbSmart** [comment]
Glad to hear you like it :) To be honest, I didn't figure out what triggered the warning, but I'm glad it's gone anyway :D
